# Generated by Django 4.2.7 on 2023-11-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="feedback_text",
        ),
        migrations.AddField(
            model_name="feedback",
            name="message",
            field=models.TextField(default="ww"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
